# Generated by Django 4.1.3 on 2022-12-01 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_tag_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='review',
            name='vote_ratio',
        ),
        migrations.RemoveField(
            model_name='review',
            name='vote_total',
        ),
        migrations.AddField(
            model_name='projects',
            name='tag',
            field=models.ManyToManyField(blank=True, to='home.tag'),
        ),
        migrations.AddField(
            model_name='projects',
            name='vote_ratio',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='vote_total',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
